apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:2.3
          ports:
            - containerPort: 4566   # LocalStack main API port
          env:
            - name: SERVICES
              value: "s3,ecr"
            - name: DEBUG
              value: "1"
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          volumeMounts:
            - name: localstack-data
              mountPath: /var/lib/localstack
      volumes:
        - name: localstack-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  selector:
    app: localstack
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
      protocol: TCP
  type: ClusterIP

